### ISSUE TITLE
image-selected not calling function

### ISSUE THREAD

**Issue by pkishino** [vermicida/ng-image-picker#3]
Hi again,
I could get it working fine when I used it directly in the controller, but when I move the whole thing to a $uibModal then the image-selected="$ctrl.myselectionFunction" is never called and hence I cannot set the image :(

**Comment by vermicida** [comment]
Hi. Sorry for the delay. I was in vacation with no internet connection. I'm checking all my pending stuff right now.

You will use $ctrl only in component templates. The functionality you publish in a component instance (this) is accesible from the template via $ctrl reference:

```
// Component
angular.module("test").component("example", {
  controller: function() {
    this.imageSelected = function() { ... };
  }
});

// View
<image-picker image-selected="$ctrl.imageSelected()"></image-picker>
```

But in other AngularJS tools, like controllers or directives, you don't need the $ctrl reference in the view, so you can omit it. You just need to publish the handler in the $scope:

```
// Controller
angular.module("test").controller("example", function($scope) {
  $scope.imageSelected = function() { ... };
});

// View
<image-picker image-selected="imageSelected()"></image-picker>
```

Try to change it and write me back if it didn't worked.
